version: "3.8"
services:

  api:
    image: 192479299400.dkr.ecr.ap-southeast-1.amazonaws.com/sit-careers-api:api
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    working_dir: /app
    container_name: sit-careers-api
    restart: always
    volumes:
      - api:/app
    ports:
        - "9000"
    env_file:
      - .sit-cc-api.env
    networks:
      - sit-careers

  api-nginx:
    image: 192479299400.dkr.ecr.ap-southeast-1.amazonaws.com/sit-careers-api:nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    working_dir: /etc/nginx
    container_name: sit-careers-api-nginx
    restart: always
    volumes:
      - api:/app
    ports:
      - "8000:80"
    networks:
      - sit-careers

  phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      restart: always
      container_name: sit-careers-myadmin
      ports:
          - "8080:80"
      environment:
          PMA_HOST: ${DB_HOST}
      networks:
          - sit-careers

volumes:
  api:

networks:
  sit-careers:
    driver: bridge
