version: "3.8"
services:

  api:
    image: sit-careers-api:api-test-${IMAGE_TAG}
    working_dir: /app
    env_file:
      - testing.env
    networks:
      - sit-careers

networks:
  sit-careers:
    driver: bridge
