version: "3.8"
services:

  api:
    image: sit-careers-api:api
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    working_dir: /app
    container_name: sit-careers-api
    restart: always
    volumes:
      - api:/api/app
    ports:
        - "9000"
    env_file:
      - .sit-cc-api.env
    networks:
      - sit-careers

  api-nginx:
    image: sit-careers-api:nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    working_dir: /etc/nginx
    container_name: sit-careers-api-nginx
    restart: always
    volumes:
      - api:/app
      - /var/log/nginx:/var/log/nginx
    ports:
      - "8080:80"
    networks:
      - sit-careers

volumes:
  api:

networks:
  sit-careers:
    driver: bridge
